In [1]:
import numpy as np

### Array mathematics

In [3]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [4]:
a + b

array([ 6.,  4.,  9.])

In [5]:
a/b

array([ 0.2,  1. ,  0.5])

In [6]:
a % b

array([ 1.,  0.,  3.])

In [7]:
b % a

array([ 0.,  0.,  0.])

In [8]:
b**a #power

array([   5.,    4.,  216.])

In [10]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([1, 100], float)
a + b

array([[   2.,  102.],
       [   4.,  104.],
       [   6.,  106.]])

In [12]:
np.array([-1, 3], float)

array([-1.,  3.])

In [13]:
b = np.array([-1., 3.], float)
b

array([-1.,  3.])

In [14]:
 b[:,np.newaxis]

array([[-1.],
       [ 3.]])

In [15]:
 b[:,]

array([-1.,  3.])

In [18]:
b[:,]

array([-1.,  3.])

In [21]:
x = b[:,np.newaxis]
x

array([[-1.],
       [ 3.]])

In [23]:
x.shape

(2, 1)

In [24]:
 b[np.newaxis,:]

array([[-1.,  3.]])

In [29]:
arr = np.arange(4)
print arr.shape
arr

(4,)


array([0, 1, 2, 3])

In [32]:
arr = np.arange(4)
arr[np.newaxis,:]

array([[0, 1, 2, 3]])

In [33]:
col_vec = arr[:, np.newaxis]

In [34]:
col_vec.shape

(4, 1)

In [36]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [38]:
for (x, y) in a:
    print x+y

2.0
2.0
8.0


In [40]:
#equivalent but much much faster
a.sum(axis=1)

array([ 2.,  2.,  8.])

### Basic array operations

In [42]:
a = np.array([2, 4, 3], float)
print a.sum()
print a.prod()

9.0
24.0


In [43]:
a.std()

0.81649658092772603

In [48]:
np.sqrt(((a - a.mean())**2).sum()/a.size)

0.81649658092772603

In [51]:
#The argmin and argmax functions return the array indices of the minimum and maximum values:
a = np.array([10, 100, 0, 9999], float)
print a.argmax()
print a.argmin()

3
2


In [58]:
a = np.array([[0, 200], [3, -1], [3, 5]], float)
a

array([[   0.,  200.],
       [   3.,   -1.],
       [   3.,    5.]])

In [59]:
a.mean(axis=0)

array([  2.,  68.])

In [60]:
a.mean(axis=1)

array([ 100.,    1.,    4.])

In [61]:
a.min(axis=1)

array([ 0., -1.,  3.])

In [62]:
a.max(axis=0)

array([   3.,  200.])