In [1]:
import numpy as np

### Array mathematics

In [3]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [4]:
a + b

array([ 6.,  4.,  9.])

In [5]:
a/b

array([ 0.2,  1. ,  0.5])

In [6]:
a % b

array([ 1.,  0.,  3.])

In [7]:
b % a

array([ 0.,  0.,  0.])

In [8]:
b**a #power

array([   5.,    4.,  216.])

In [10]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([1, 100], float)
a + b

array([[   2.,  102.],
       [   4.,  104.],
       [   6.,  106.]])

In [12]:
np.array([-1, 3], float)

array([-1.,  3.])

In [13]:
b = np.array([-1., 3.], float)
b

array([-1.,  3.])

In [14]:
 b[:,np.newaxis]

array([[-1.],
       [ 3.]])

In [15]:
 b[:,]

array([-1.,  3.])

In [18]:
b[:,]

array([-1.,  3.])

In [21]:
x = b[:,np.newaxis]
x

array([[-1.],
       [ 3.]])

In [23]:
x.shape

(2, 1)

In [24]:
 b[np.newaxis,:]

array([[-1.,  3.]])

In [29]:
arr = np.arange(4)
print arr.shape
arr

(4,)


array([0, 1, 2, 3])

In [32]:
arr = np.arange(4)
arr[np.newaxis,:]

array([[0, 1, 2, 3]])

In [33]:
col_vec = arr[:, np.newaxis]

In [34]:
col_vec.shape

(4, 1)

In [36]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [38]:
for (x, y) in a:
    print x+y

2.0
2.0
8.0


In [40]:
#equivalent but much much faster
a.sum(axis=1)

array([ 2.,  2.,  8.])

### Basic array operations

In [42]:
a = np.array([2, 4, 3], float)
print a.sum()
print a.prod()

9.0
24.0


In [43]:
a.std()

0.81649658092772603

In [48]:
np.sqrt(((a - a.mean())**2).sum()/a.size)

0.81649658092772603

In [51]:
#The argmin and argmax functions return the array indices of the minimum and maximum values:
a = np.array([10, 100, 0, 9999], float)
print a.argmax()
print a.argmin()

3
2


In [58]:
a = np.array([[0, 200], [3, -1], [3, 5]], float)
a

array([[   0.,  200.],
       [   3.,   -1.],
       [   3.,    5.]])

In [59]:
a.mean(axis=0)

array([  2.,  68.])

In [60]:
a.mean(axis=1)

array([ 100.,    1.,    4.])

In [61]:
a.min(axis=1)

array([ 0., -1.,  3.])

In [62]:
a.max(axis=0)

array([   3.,  200.])

In [63]:
a = np.array([6, 2, 5, -1, 0], float)

In [65]:
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [66]:
a

array([ 6.,  2.,  5., -1.,  0.])

#### Values in an array can be "clipped" to be within a prespecified range. This is the same as
applying min(max(x, minval), maxval) to each element x in an array. Like winsorization

In [71]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0,5)

array([ 5.,  2.,  5.,  0.,  0.])

In [72]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([ 1.,  4.,  5.,  7.])

In [73]:
a = np.array([[1, 2], [3, 4]], float)
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [74]:
a.diagonal()

array([ 1.,  4.])

In [75]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b

array([ True, False, False], dtype=bool)

In [76]:
a < b

array([False, False,  True], dtype=bool)

In [77]:
a == b

array([False,  True, False], dtype=bool)

In [81]:
 np.logical_and(a > b, a < b)

array([False, False, False], dtype=bool)

In [86]:
np.logical_or(np.logical_or(a > b, b > a), a == b)

array([ True,  True,  True], dtype=bool)

In [87]:
a = np.array([1, 3, 0], float)
a > 2

array([False,  True, False], dtype=bool)

#### The any and all operators can be used to determine whether or not any or all elements of a
Boolean array are true:

In [90]:
c = np.array([ True, False, False], bool)
any(c)

True

In [91]:
all(c)

False

The *** where ***  function forms a new array from two arrays of equivalent size using a Boolean filter to choose between elements of the two. Its basic syntax is where(boolarray,
truearray, falsearray):

In [96]:
a = np.array([1, 3, 0], float)
np.where(a != 0.0, 1.0/a, a)

/Users/jvsingh/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in divide
  from ipykernel import kernelapp as app


array([ 1.        ,  0.33333333,  0.        ])

In [97]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

A number of functions allow testing of the values in an array. The *** nonzero *** function gives a tuple of indices of the nonzero values in an array. The number of items in the tuple equals the number of axes of the array:

In [111]:
a = np.array([[10, 0], [0, 5]], float)
print a
a.nonzero()

[[ 10.   0.]
 [  0.   5.]]


(array([0, 1]), array([0, 1]))

In [113]:
a = np.array([[10, 1], [3, 0]], float)
print a
a.nonzero()

[[ 10.   1.]
 [  3.   0.]]


(array([0, 0, 1]), array([0, 1, 0]))

#### It is also possible to test whether or not values are NaN ("not a number") or finite:

In [114]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([  1.,  nan,  inf])

In [115]:
np.isnan(a)

array([False,  True, False], dtype=bool)

In [116]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

#### Array item selection and manipulation

In [118]:
a = np.array([[6, 4], [5, 9]], float)
print a
a >= 6
print a >= 6

[[ 6.  4.]
 [ 5.  9.]]
[[ True False]
 [False  True]]


In [119]:
sel = (a >= 6)
a[sel]

array([ 6.,  9.])

In [120]:
sel = a > 0
a[sel]

array([ 6.,  4.,  5.,  9.])

In [121]:
a[np.logical_and(a > 5, a < 9)]

array([ 6.])

##### Selection using integer arrays

In [122]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

##### Lists can also be used as selection arrays:

In [123]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

#### Multidimensional selection

In [124]:
a = np.array([[1, 4], [9, 16]], float)
print a

[[  1.   4.]
 [  9.  16.]]


In [125]:
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] #first index for first array and second from second array

array([  1.,   4.,  16.,  16.,   4.])

In [127]:
# ** take *** function
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [128]:
a = np.array([[0, 1], [2, 3]], float)
a

array([[ 0.,  1.],
       [ 2.,  3.]])

In [129]:
b = np.array([0, 0, 1], int)

In [130]:
a.take(b, axis=0)

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 2.,  3.]])

In [131]:
a.take(b, axis=1)

array([[ 0.,  0.,  1.],
       [ 2.,  2.,  3.]])

*** put *** function (opposite of take)

In [132]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b)
a

array([ 9.,  1.,  2.,  8.,  4.,  5.])