In [1]:
import rpy2
import rpy2.robjects as robjects
from rpy2.robjects.packages import importr, data

In [2]:
dlm = importr('dlm')

R Code
```R
rw <- dlm(m0 = 0, C0 = 10, FF = 1, V = 1.4, GG = 1, W = 0.2)
```

In [3]:
rw  = dlm.dlm(m0 = 0, C0 = 10, FF = 1, V = 1.4, GG = 1, W = 0.2)

In [4]:
rw

<rpy2.robjects.vectors.ListVector object at 0x10ed275c0> [RTYPES.VECSXP]
R classes: ('dlm',)
[IntSe..., IntSe..., IntSe..., Float..., IntSe..., Float...]
  m0: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10e2eb500> [RTYPES.INTSXP]
  C0: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10df692c0> [RTYPES.INTSXP]
  FF: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10ddb3f40> [RTYPES.INTSXP]
  V: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10ed18c00> [RTYPES.REALSXP]
  GG: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10ed18e40> [RTYPES.INTSXP]
  W: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x10ed144c0> [RTYPES.REALSXP]

In [5]:
rw[0]

<rpy2.robjects.vectors.IntVector object at 0x10e317940> [RTYPES.INTSXP]
R classes: ('integer',)
[0]

In [6]:
rw.rx2('m0')

<rpy2.robjects.vectors.IntVector object at 0x10ed222c0> [RTYPES.INTSXP]
R classes: ('integer',)
[0]

In [7]:
rw[1]

<rpy2.robjects.vectors.IntMatrix object at 0x10ed0de80> [RTYPES.INTSXP]
R classes: ('matrix', 'array')
[10]

In [8]:
rw.rx2('C0')

<rpy2.robjects.vectors.IntMatrix object at 0x10ed04500> [RTYPES.INTSXP]
R classes: ('matrix', 'array')
[10]

In [9]:
{k:v for k,v in rw.items()}['m0']

<rpy2.robjects.vectors.IntVector object at 0x10ed70d40> [RTYPES.INTSXP]
R classes: ('integer',)
[0]

In [10]:
{k:v for k,v in rw.items()}['C0']

<rpy2.robjects.vectors.IntMatrix object at 0x10ed8cb40> [RTYPES.INTSXP]
R classes: ('matrix', 'array')
[10]

In [11]:
import numpy as np
np.matrix(rw.rx2('C0'))

matrix([[10]], dtype=int32)

In [12]:
rw.rx2('W')

<rpy2.robjects.vectors.FloatMatrix object at 0x10ed2c9c0> [RTYPES.REALSXP]
R classes: ('matrix', 'array')
[0.200000]

In [13]:
x = robjects.ListVector({'a': 1, 'b': 2, 'c': 3})

In [14]:
print(x)

$a
[1] 1

$b
[1] 2

$c
[1] 3




In [15]:
x.names.index('b')

1

In [16]:
x[x.names.index('b')] = 9

In [17]:
x

<rpy2.robjects.vectors.ListVector object at 0x10dd8d3c0> [RTYPES.VECSXP]
R classes: ('list',)
[IntSexpVector, IntSexpVector, IntSexpVector]
  a: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10f71a140> [RTYPES.INTSXP]
  b: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10f71a440> [RTYPES.INTSXP]
  c: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x10f71a580> [RTYPES.INTSXP]

In [18]:
print(x)

$a
[1] 1

$b
[1] 9

$c
[1] 3




R code:

```R
lg <- dlm(m0 = rep(0,2), 
          C0 = 10 * diag(2), 
          FF = matrix(c(1,0),nr=1), 
          V = 1.4, GG = matrix(c(1,0,1,1),nr=2), 
          W = diag(c(0,0.2)))
```

In [19]:
m0 = robjects.r.matrix(robjects.FloatVector([0,0]), nrow=2)
C0 =  robjects.r.matrix(robjects.FloatVector(list(10 * np.eye(2).ravel())), nrow=2)
FF =  robjects.r.matrix(robjects.FloatVector([1, 0]), nrow=1)
GG =  robjects.r.matrix(robjects.FloatVector([1, 0, 1, 1]), nrow=2)
W =  robjects.r.matrix(robjects.FloatVector(list(np.diag([0, 0.2]).ravel())), nrow=2)
print(W)
lg  = dlm.dlm(m0 = m0 , 
              C0 = C0, 
              FF = FF, 
              V = 1.4, 
              GG = GG, 
              W = W)

     [,1] [,2]
[1,]    0  0.0
[2,]    0  0.2



In [20]:
print(lg)

$FF
     [,1] [,2]
[1,]    1    0

$V
     [,1]
[1,]  1.4

$GG
     [,1] [,2]
[1,]    1    1
[2,]    0    1

$W
     [,1] [,2]
[1,]    0  0.0
[2,]    0  0.2

$m0
     [,1]
[1,]    0
[2,]    0

$C0
     [,1] [,2]
[1,]   10    0
[2,]    0   10




In [21]:
print(lg.names)
print(lg.names.index("W"))
print(lg[lg.names.index("W")])
print(lg.rx2('W'))

[1] "m0" "C0" "FF" "V"  "GG" "W" 

5
     [,1] [,2]
[1,]    0  0.0
[2,]    0  0.2

     [,1] [,2]
[1,]    0  0.0
[2,]    0  0.2



### Dynamic regression model

$$
\begin{align}
Y_t &= \theta_1 + \theta_2 x_t + \epsilon_t\\
\begin{bmatrix} 
    \theta_1 \\ \theta_2 \end
{bmatrix}_t &=  \begin{bmatrix}
                1 & 0\\
                0 & 1
               \end{bmatrix} \begin{bmatrix} 
                                 \theta_1 \\ \theta_2
                              \end{bmatrix}_{t-1}   +  \epsilon  
\end{align}
$$

```R
x <- rnorm(100) # covariates
dlr <- dlm(m0 = rep(0,2), 
           C0 = 10 * diag(2), 
           FF = matrix(c(1,0),nr=1),
           V = 1.3, 
           GG = diag(2), 
           W = diag(c(0.4,0.2)),
           JFF = matrix(c(0,1),nr=1), 
           X = as.matrix(x))
```

In [22]:
# Time varying x
x = np.random.randn(100)
m0 = robjects.r.matrix(robjects.FloatVector([0,0]), nrow=2)
C0 =  robjects.r.matrix(robjects.FloatVector(list(10 * np.eye(2).ravel())), nrow=2)
FF =  robjects.r.matrix(robjects.FloatVector([1, 0]), nrow=1)
V = 1.3
GG =  robjects.r.matrix(robjects.FloatVector(np.eye(2).ravel()), nrow=2)
W =  robjects.r.matrix(robjects.FloatVector(np.diag([0.4, 0.2]).ravel()), nrow = 2)
JFF =  robjects.r.matrix(robjects.FloatVector([0, 1]), nrow = 1)
X =  robjects.r.matrix(robjects.FloatVector(x), ncol = 1)


dlr = dlm.dlm(m0 = m0, 
           C0 = C0, 
           FF = FF,
           V = V, 
           GG = GG, 
           W =W,
           JFF = JFF, 
           X = X)


In [23]:
print(dlr)

$FF
     [,1] [,2]
[1,]    1    0

$V
     [,1]
[1,]  1.3

$GG
     [,1] [,2]
[1,]    1    0
[2,]    0    1

$W
     [,1] [,2]
[1,]  0.4  0.0
[2,]  0.0  0.2

$JFF
     [,1] [,2]
[1,]    0    1

$X
     [,1]  
[1,] 0.413 
[2,] 0.6488
[3,] ...   

$m0
     [,1]
[1,]    0
[2,]    0

$C0
     [,1] [,2]
[1,]   10    0
[2,]    0   10




In [24]:
# Note we put second elemnt of FF 0 as it is time varying and is set in X
# We can see JFF.. match with $X above.. 
x[0:10]

array([ 0.41299054,  0.64882501,  0.47088652, -0.51628465, -0.57470014,
        0.39974819, -0.94867716,  1.65265026, -0.34906876, -0.33566113])

### R Code

```R
#-------------------------------------------------------------------------------
#Generate some data first - toy example
#Kalman filter/dynamic linear model in R
#-------------------------------------------------------------------------------
rm(list=ls())
set.seed(100)
df <- data.frame(x1 = sample(seq(from = -1.0, by = 0.01, length.out = 1000), 
                               size = 1000, replace = FALSE),
                 x2 = sample(seq(from = -3.0, by = 0.01, length.out = 1000), 
                               size = 1000, replace = FALSE))

theta1 <- 0.4
theta2 <- 1.2
y      <- sum(df[1, ] * c(theta1[1], theta2[1])) + rnorm(1, mean = 0, sd = 0.01)

for(i in 2:1000)
{
  theta1 <- c(theta1, theta1[i-1] + rnorm(1, mean = 0, sd = 0.01))
  theta2 <- c(theta2, theta2[i-1] + rnorm(1, mean = 0, sd = 0.02))
  y      <- c(y, sum(df[i, ] * c(theta1[i], theta2[i])) + rnorm(1, mean = 0, sd = 0.01))
}


df[["y"]] <- y
df[["tim"]] <- 1:length(y)
```

In [25]:
import pandas as pd
np.random.seed(144)
# Not exactly above.. but
df = pd.DataFrame({
              "x1": np.random.choice(np.linspace(-1, 1, num=1000), size=1000, replace=False),
              "x2": np.random.choice(np.linspace(-3, 3, num=1000), size=1000, replace=False)
             })
theta1 = 0.4
theta2 = 1.2

# Theta evolution
theta_1_shocks = np.random.normal(loc=0.0,
                                  scale=0.01,
                                  size=df.shape[0]-1)
theta_2_shocks = np.random.normal(loc=0.0,
                                  scale=0.02,
                                  size=df.shape[0]-1)

theta_1_shocks = np.insert(theta_1_shocks, 0,0)
theta1_s = theta1 + theta_1_shocks.cumsum()
theta_2_shocks = np.insert(theta_2_shocks, 0,0)
theta2_s = theta2 + theta_2_shocks.cumsum()

y_shocks = np.random.normal(loc=0.0, scale=0.01, size=df.shape[0])

y = np.apply_along_axis(sum, 1, df[["x1", "x2"]] * np.vstack([theta1_s, theta2_s]).T) + y_shocks

df["y"] = y

In [26]:
df

x1        x2         y
0   -0.049049  2.273273  2.720595
1   -0.757758  0.771772  0.595450
2    0.855856 -1.648649 -1.554209
3   -0.519520 -1.942943 -2.456723
4    0.245245 -1.876877 -2.009597
..        ...       ...       ...
995 -0.155155 -0.579580 -1.304476
996 -0.567568  2.189189  4.708195
997  0.781782 -0.465465 -0.856264
998 -0.111111 -0.855856 -1.916291
999 -0.281281  0.981982  2.125421

[1000 rows x 3 columns]

## R Code

```R
#-------------------------------------------------------------------------------
#Learn MLE from first 500
#-------------------------------------------------------------------------------

buildFn <- function(x)
{
  ret.mod <- dlm::dlmModReg(X = as.matrix(df[1:500, c("x1", "x2")]),
                            dV = exp(x[3]), 
                            dW = exp(x[1:2]), 
                            addInt = FALSE)
  ret.mod
}

fit <- dlm::dlmMLE( y     = df$y[1:500], 
                    build = buildFn, 
                    parm  = log(c(rep(1e2, 2), 1e2)),
                    lower = log(rep(1e-5, 3)), 
                    hessian=TRUE)


mod.res <- buildFn(fit$par)
avarLog <- solve(fit$hessian)
avar <- diag(exp(fit$par)) %*% avarLog %*% diag(exp(fit$par)) # Delta method
V(mod.res)
W(mod.res)

```


# https://rpy2.github.io/doc/v3.5.x/html/robjects_functions.html

# SEEMS to much of work... let me stop here and look for proper implemtation of library
found one here:
https://brandonwillard.github.io/dynamic-linear-models-in-theano.html


In [47]:
r_func_code = """

function(x){
   c(mean(x), sd(x))
}
"""

r_func = robjects.r(r_func_code)

py_func = robjects.functions.wrap_r_function(r_func, 'py_func')


In [49]:
py_func(robjects.FloatVector([1,2,3]))

<rpy2.robjects.vectors.FloatVector object at 0x150cad580> [RTYPES.REALSXP]
R classes: ('numeric',)
[2.000000, 1.000000]

In [67]:
# Try decorator kind - 

r_func_code = """
function(const){
  # MLE Estimator
  finternal <- function(x){
    c(mean(x) + const, sd(x) + const)
  }
  finternal
}
"""

r_func = robjects.r(r_func_code)

py_func_g = robjects.functions.wrap_r_function(r_func, 'g')


In [68]:
py_func_g(10)(robjects.FloatVector([1,2,3]))

<rpy2.robjects.vectors.FloatVector object at 0x150cb6a80> [RTYPES.REALSXP]
R classes: ('numeric',)
[12.000000, 11.000000]

In [92]:
## We try MLE estimator of Variance matrices
# I think we can do exponential moveing average estimator of covariance matrix as estimate of V then 
# we may not need MLE estimator

r_func_code_mle = """
function(df){
  # MLE estimator
  buildFn <- function(x)
  {
      ret.mod <- dlm::dlmModReg(X = as.matrix(df[1:500, c("x1", "x2")]),
                            dV = exp(x[3]), 
                            dW = exp(x[1:2]), 
                            addInt = FALSE)
      ret.mod
  }
  fit <- dlm::dlmMLE( y  = df$y[1:500], 
                    build = buildFn, 
                    parm  = log(c(rep(1e2, 2), 1e2)),
                    lower = log(rep(1e-5, 3)), 
                    hessian=TRUE)
  mod.res <- buildFn(fit$par)
  avarLog <- solve(fit$hessian)
  avar <- diag(exp(fit$par)) %*% avarLog %*% diag(exp(fit$par))  
  return(list(V = V(mod.res), W =  W(mod.res)))
}
"""

r_func_mle = robjects.r(r_func_code_mle)

py_func_mle = robjects.functions.wrap_r_function(r_func_mle, 'mle')



In [93]:
## dict(df)

d = {}
for col in df.columns:
    print(col)
    d[col] = robjects.FloatVector(df[col].values)

df_r = robjects.DataFrame(d)

result_mle = py_func_mle(df_r)


x1
x2
y


In [98]:
result_mle.names
print(result_mle.rx2('V'))
print(result_mle.rx2('W'))

             [,1]
[1,] 7.025874e-05

             [,1]         [,2]
[1,] 7.089558e-05 0.0000000000
[2,] 0.000000e+00 0.0004870542

