##### From Rajat Mongas Presentation: https://youtu.be/wmw8Bbb_eIE


In [2]:
import tensorflow as tf

Skeleton of a program:

In [3]:
#Create a session with TensorFlow runtime
with tf.Session() as sess:
    #Define some ops
    c = tf.constant("Hello World")
    #print addess of session object
    print("Address of session object %s" % (hex(id(c))))
    # Run a step
    print(sess.run(c))

Address of session object 0x11193cdd8
b'Hello World'


In [5]:
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'f: hello world'

xx = MyClass()
xx.f()

'f: hello world'

#### Arbitrary class gives an error 

It seems constant can be 

In [6]:
#Create a session with TensorFlow runtime
with tf.Session() as sess:
    #Define some ops
    temp = MyClass()
    c = tf.constant(temp)
    #print addess of session object
    print("Address of session object %s" % (hex(id(c))))
    # Run a step
    print(sess.run(c))

TypeError: Expected binary or unicode string, got <__main__.MyClass object at 0x11193cd68>

In [7]:
import numpy as np
#Create a session with TensorFlow runtime
with tf.Session() as sess:
    a = tf.constant([1.0, 2.0, 3.0, 4.0])  #float32
    b = tf.constant([3,4,5])
    c = tf.constant([5,6,7,8], shape=[2,2])
    d = tf.constant(np.random.rand(2,4,6))

In [8]:
d
print (d)

Tensor("Const_4:0", shape=(2, 4, 6), dtype=float64)


In [9]:
np.random.rand(2,4,6)

array([[[ 0.35992928,  0.29476715,  0.6006    ,  0.73412845,  0.96780918,
          0.46567694],
        [ 0.47631527,  0.15694918,  0.03397722,  0.1610979 ,  0.00518381,
          0.14218394],
        [ 0.63221772,  0.89198585,  0.41807885,  0.70755764,  0.33412763,
          0.33706993],
        [ 0.3095915 ,  0.26908813,  0.51070892,  0.19332134,  0.93862439,
          0.84923642]],

       [[ 0.72183006,  0.30057935,  0.78026356,  0.35433134,  0.80425204,
          0.27942562],
        [ 0.33036314,  0.69899428,  0.16168716,  0.4438305 ,  0.54987427,
          0.13941623],
        [ 0.44249986,  0.11083745,  0.02889702,  0.2514695 ,  0.96937208,
          0.79395406],
        [ 0.60047785,  0.73132   ,  0.18971409,  0.02629048,  0.51667264,
          0.76434487]]])

In [14]:
x = tf.constant([5,6,7,8], shape=[2,2])
print("First: %s" % x.__repr__())

x = tf.constant([5,6,7,8], shape=[1,4])
print("Second:%s" % x)

print(x.get_shape())

y = x.get_shape()[1]
print(y)
print(y.__repr__())
print(y.value)

First: <tf.Tensor 'Const_11:0' shape=(2, 2) dtype=int32>
Second:Tensor("Const_12:0", shape=(1, 4), dtype=int32)
(1, 4)
4
Dimension(4)
4


In [15]:
hex(id(x))

'0x1119be0b8'

In [16]:
def createList():
    x = [1,2,3]
    print("createList:: Address of x %s" % hex(id(x)))
    return(x)
    

In [17]:
y = createList()

createList:: Address of x 0x1119c4e08


In [18]:
hex(id(y))

'0x1119c4e08'

In [19]:
### Operations build the dataflow graph; eval fetches the result

In [20]:
with tf.Session():
    x = tf.constant([[5,6], [7,8]])
    z = tf.matmul(x,x) + tf.matmul(x, [[1,0], [1,0]])
    #No execution - only graph build up till now
    result = z.eval() #runs now : Shorthand for sess.run()

#### Variables

In [32]:
with tf.Session():
    v = tf.Variable([[0., 0.]]) #initial value
    #variable initialization has NOT happened so far
    
    tf.global_variables_initializer().run()  #if you forget this, tensoflow will fail
    #Initialization of variables done now
    
    print(v.eval())   #Prints a 1x2 zero ndarray
    
    assign_op = v.assign(tf.constant([[1.0, 2.0]]))
    #assign_op.run()
    print(assign_op.eval())
    

[[ 0.  0.]]
[[ 1.  2.]]


In [33]:
### Batch Logistic Regression

In [ ]:
#Create new computation graph
graph = tf.Graph()

with graph.AsDefault():
    #Training data/labels
    examples = tf.constant(train_dataset)
    labels   = tf.constant(train_labels)
    
    #Variables
    W = tf.Variable(tf.truncated_normal([image_size * image_size, num_labels]))
    b = tf.Variable(tf.zeros([num_labels]))
    
    #Training computation
    logits = tf.mat_mul(examples, W) + b
    loss   = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits, labels))
    
    #Optimizer to use
    optimizer = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
    
    #Predictions for training data
    prediction = tf.nn.softmax(logits)
    
    

In [ ]:
#### K-means clustering using tensor flow


In [37]:
# 'x' are the points to be clusteres, 'k' is number of clusters

centroids = tf.Variable(tf.random_normal([k, x.shape[1]]))

distances = tf.pdist2(x, centroids)

nearest = tf.argmin(distances, 1)

update = tf.assign(centroids, tf.segment_mean(x, nearest))


with tf.Session() as session:
    tf.initialize_all_variables().Run()
    for step in xrange(100):
        session.Ru(update)

NameError: name 'k' is not defined