Taken from "Python Engineer" @ https://www.youtube.com/watch?v=DbeIqrwb_dE|

In [10]:
import torch

In [11]:
# requires_grad = True 
# This tells that we will require to calculate gradient of some function wrt x
#  x
#   \
#    [+] -> y
#   /
#  2

x = torch.randn(3, requires_grad = True)

In [12]:
print(x)

tensor([0.0137, 1.4403, 0.5618], requires_grad=True)


In [13]:
y = x + 2
print(y)

tensor([2.0137, 3.4403, 2.5618], grad_fn=<AddBackward0>)


We see that AddBackward0 function there

In [14]:
z = y*y *2
print(z)

tensor([ 8.1098, 23.6720, 13.1259], grad_fn=<MulBackward0>)


In [15]:
# This gives error as we still dont have a scalar output z.  z is vector as of now
#z.backward()  # will give dz/dx
#print(x.grad) 

In [16]:
z = z.mean()
print(z)

tensor(14.9692, grad_fn=<MeanBackward0>)


In [17]:
z.backward()  # will give dz/dx
print(x.grad)        # attribute which stores gradients

tensor([2.6849, 4.5871, 3.4158])
